AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: 
  Subnet1Id:
    Type: AWS::EC2::Subnet::Id
  Subnet2Id:
    Type: AWS::EC2::Subnet::Id
  CidrIp1:
    Type: String
    Description: Provide the ip address of first instance in '/32' format
  CidrIp2:
    Type: String
    Description: Provide the ip address of second instance in '/32' format
  InstanceIpAddress1:
    Type: String
  InstanceIpAddress2:
    Type: String

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref Cidrip1
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp1: !Ref CidrIp2

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB
      Subnets:
        - !Ref Subnet1Id
        - !Ref Subnet2Id
      Scheme: internal
      SecurityGroups:
        - !Ref AlbSecurityGroup
    DependsOn:
      - ListenerHTTPS

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup1
        - Type: forward
          TargetGroupArn: !Ref TargetGroup2
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS

  TargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TargetGroup1
      Port: 443
      Protocol: HTTPS
      VpcId: !Ref VpcId
      TargetType: 'ip'
      Targets:
        - Id: !Ref InstanceIpAddress1
          Port: 443

  TargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TargetGroup2
      Port: 443
      Protocol: HTTPS
      VpcId: !Ref VpcId
      TargetType: 'ip'
      Targets:
        - Id: !Ref InstanceIpAddress2
          Port: 443
