Parameters:
  EmailAddress1:
    Type: String
    Default: 'venkatesh.s.soma@gmail.com'

  EmailAddress2:
    Type: String
    Default: 'santosh.gupta191@gmail.com'

Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS-Topic-For-Config-Rule-Alerts

  EmailSubscription1:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref EmailAddress1

  EmailSubscription2:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref EmailAddress2

  ConfigRoleRavi:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AWSConfigRoleRavi
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: SecurityGroupPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeNetworkInterfaces'
                Resource: '*'
        - PolicyName: SSMPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                Resource: '*'

  AWSConfigRuleRavi:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: restricted-common-ports-ravi
      Description: >-
        Checks whether the security group of EC2 instances allows unrestricted
        incoming TCP traffic to the specified ports.
      Scope:
        ComplianceResourceTypes:
          - 'AWS::EC2::SecurityGroup'
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
      InputParameters:
        blockedPort1: '22'
        blockedPort2: '3389'

  RemediationConfigurations:
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: !Ref AWSConfigRuleRavi
      TargetType: SSM_DOCUMENT
      TargetId: AWS-DisablePublicAccessForSecurityGroup
      TargetVersion: $LATEST
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt ConfigRoleRavi.Arn
        GroupId:
          ResourceValue:
            Value: "RESOURCE_ID"
        IpProtocol:
          StaticValue:
            Values:
              - '-1'
        CidrBlock:
          StaticValue:
            Values:
              - 0.0.0.0/0
      ResourceType: 'AWS::EC2::SecurityGroup'
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60

  ConfigRuleCloudWatchEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: CloudWatch Events rule to trigger AWS Config rule evaluation.
      EventPattern:
        source:
          - aws.config
        detail-type:
          - Config Rules Compliance Change
        detail:
          MessageType:
            - ComplianceChangeNotification
          ConfigRuleName:
            - !Ref AWSConfigRuleRavi
      State: ENABLED
      Targets:
        - Arn: !Ref SNSTopic
          Id: "TargetSNSTopic"
          InputTransformer:
            InputPathsMap:
              "awsRegion": "$.detail.awsRegion"
              "complianceType": "$.detail.newEvaluationResult.complianceType"
              "resourceId": "$.detail.resourceId"
            InputTemplate: |
              "The resource <resourceId> in region <awsRegion> had an inbound rule open to internet for port 22/3389 and is being automatically removed as per security guidelines"
